### 
POST http://localhost:8080/api/accounts 
Content-Type: application/json

{
    "accountHolderName": "Test",
    "balance": 20
}

### 
GET http://localhost:8080/api/accounts/1

### 
PUT http://localhost:8080/api/accounts/4/deposit
Content-Type: application/json

{
    "amount": 20
}

### 
PUT http://localhost:8080/api/accounts/4/withdraw
Content-Type: application/json

{
    "amount": 20
}

### 
GET http://localhost:8080/api/accounts

### 
DELETE http://localhost:8080/api/accounts/4/delete